%% Robot Plot
% This file takes the Robot generated by the PC Robotics toolbox shows and
% animation describing the range of motion
global R NLinks a_link
q0 = zeros(1,NLinks);
qlims = R.qlim;
q_plot = zeros(100,NLinks);
ran = randi(100,1);
for i = 1:NLinks
   q_plot(:,i) = linspace(qlims(i,1),qlims(i,2))';
end
qp = q_plot(ran,:);
WS = [-1 1 -1 1 -1 1].*(NLinks*max(a_link,[],'all'));

figure(2)
R.plot(qp,'workspace',WS);
R.teach(qp)

